name: Run Brit Insurance Web Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Run Tests
        run: mvn clean verify
      - name: Publish Serenity Report
        run: |
          mkdir -p ${{ github.workspace }}/docs
          cp -R target/site/serenity/* ${{ github.workspace }}/docs/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs