name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build and Run Tests
        run: mvn clean verify
      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/site/serenity